/*
 *
 * WEATHER constants
 *
 */

export const WEATHER_WATCHER = 'app/CALENDARY/WEATHER_WATCHER';
export const WEATHER_SUCCESS = 'app/CALENDARY/WEATHER_SUCCESS';
export const WEATHER_FAILED = 'app/CALENDARY/WEATHER_FAILED';
